version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'upgrade'
      include: 'scope'
    target-branch: 'main'
    labels:
      - 'dependencies'
      - 'python'
    reviewers:
      - 'dev-team'
    milestone: 1
